import { DEFAULT_OVERVIEW_CHART } from "@/lib/overview-chart";
import { DEFAULT_OVERVIEW_WIDGETS } from "@/lib/overview-widgets";
import type { PortfolioDataPayload } from "@/lib/portfolio-data";
import type { User } from "@/types";

/** Read-only sample portfolio (~$1.2M net worth). No wallets tab; fake names throughout. */
export function getDemoAccount(): User {
  return {
    id: "demo",
    tenant: "demo",
    displayName: "Demo",
    email: "demo.user@example.com",
    username: "demo",
  };
}

export function getDemoPortfolioData(): PortfolioDataPayload {
  return {
    sectionGroups: [
      { id: "grp-retirement", page: "assets", name: "Retirement", order: 0 },
      { id: "grp-investments", page: "assets", name: "Investments", order: 1 },
      { id: "grp-crypto", page: "assets", name: "Digital Assets", order: 2 },
      { id: "grp-banking", page: "cash", name: "Banking", order: 0 },
    ],
    sections: [
      {
        id: "sec-roth",
        page: "assets",
        label: "Roth IRA",
        order: 0,
        groupId: "grp-retirement",
        metadata: { account: "Fidelity" },
      },
      {
        id: "sec-taxable",
        page: "assets",
        label: "Taxable Brokerage",
        order: 0,
        groupId: "grp-investments",
        metadata: { account: "Schwab" },
      },
      {
        id: "sec-btc",
        page: "assets",
        label: "Bitcoin",
        order: 0,
        groupId: "grp-crypto",
        metadata: { isCrypto: true, account: "Coinbase" },
      },
      {
        id: "sec-cash",
        page: "cash",
        label: "Checking & Savings",
        order: 0,
        groupId: "grp-banking",
      },
      {
        id: "sec-auto",
        page: "liabilities",
        label: "Auto Loan",
        order: 0,
      },
      { id: "sec-goals", page: "planning", label: "Goals", order: 0 },
      { id: "sec-budget", page: "spending", label: "Monthly Budget", order: 0 },
    ],
    assets: [
      {
        id: "a-fxaix",
        symbol: "FXAIX",
        name: "Fidelity 500 Index",
        sectionId: "sec-roth",
        price: 154.2,
        quantity: 2500,
        costBasis: 320000,
      },
      {
        id: "a-vti",
        symbol: "VTI",
        name: "Vanguard Total Stock Market ETF",
        sectionId: "sec-taxable",
        price: 248.5,
        quantity: 1200,
        costBasis: 210000,
      },
      {
        id: "a-aapl",
        symbol: "AAPL",
        name: "Apple Inc.",
        sectionId: "sec-taxable",
        price: 212.4,
        quantity: 400,
        costBasis: 52000,
      },
      {
        id: "a-msft",
        symbol: "MSFT",
        name: "Microsoft Corp.",
        sectionId: "sec-taxable",
        price: 418.6,
        quantity: 250,
        costBasis: 68000,
      },
      {
        id: "a-nvda",
        symbol: "NVDA",
        name: "NVIDIA Corp.",
        sectionId: "sec-taxable",
        price: 132.8,
        quantity: 200,
        costBasis: 18000,
      },
      {
        id: "a-googl",
        symbol: "GOOGL",
        name: "Alphabet Inc.",
        sectionId: "sec-taxable",
        price: 176.2,
        quantity: 150,
        costBasis: 14000,
      },
      {
        id: "a-btc",
        symbol: "BTC",
        name: "Bitcoin",
        sectionId: "sec-btc",
        price: 96124,
        quantity: 2.58,
        costBasis: 95000,
        network: "Bitcoin",
        protocol: "Coinbase",
      },
    ],
    cashAccounts: [
      {
        id: "c-chase",
        name: "Chase Total Checking",
        sectionId: "sec-cash",
        balance: 12000,
      },
      {
        id: "c-ally",
        name: "Ally Online Savings",
        sectionId: "sec-cash",
        balance: 38000,
      },
      {
        id: "c-marcus",
        name: "Marcus Emergency Fund",
        sectionId: "sec-cash",
        balance: 15000,
      },
    ],
    liabilities: [
      {
        id: "l-auto",
        name: "2024 Toyota RAV4",
        sectionId: "sec-auto",
        balance: 35200,
        initialBalance: 42000,
        apy: 5.9,
      },
    ],
    planningItems: [
      {
        id: "g-retire",
        sectionId: "sec-goals",
        title: "Retirement nest egg",
        targetAmount: 2000000,
        currentAmount: 1204250,
        targetDate: "2045-01-01",
        status: "in_progress",
        notes: "On track — max Roth + brokerage contributions.",
      },
      {
        id: "g-house",
        sectionId: "sec-goals",
        title: "Vacation home down payment",
        targetAmount: 150000,
        currentAmount: 65000,
        targetDate: "2029-06-01",
        status: "in_progress",
      },
    ],
    spendingItems: [
      {
        id: "s-housing",
        sectionId: "sec-budget",
        name: "Housing",
        budget: 2800,
        spent: 2800,
        frequency: "monthly",
      },
      {
        id: "s-groceries",
        sectionId: "sec-budget",
        name: "Groceries",
        budget: 900,
        spent: 642,
        frequency: "monthly",
      },
      {
        id: "s-dining",
        sectionId: "sec-budget",
        name: "Dining out",
        budget: 450,
        spent: 318,
        frequency: "monthly",
      },
      {
        id: "s-invest",
        sectionId: "sec-budget",
        name: "Investing transfers",
        budget: 3500,
        spent: 3500,
        frequency: "monthly",
      },
    ],
    allocationNodes: [
      {
        id: "alloc-root",
        parentId: null,
        label: "Take-home pay",
        percentOfParent: 100,
        order: 0,
      },
      {
        id: "alloc-invest",
        parentId: "alloc-root",
        label: "Investments",
        percentOfParent: 25,
        order: 0,
        trackPage: "assets",
        trackSectionId: "sec-taxable",
      },
      {
        id: "alloc-roth",
        parentId: "alloc-root",
        label: "Roth IRA",
        percentOfParent: 15,
        order: 1,
        trackPage: "assets",
        trackSectionId: "sec-roth",
      },
      {
        id: "alloc-living",
        parentId: "alloc-root",
        label: "Living expenses",
        percentOfParent: 45,
        order: 2,
      },
      {
        id: "alloc-save",
        parentId: "alloc-root",
        label: "Cash savings",
        percentOfParent: 15,
        order: 3,
        trackPage: "cash",
        trackSectionId: "sec-cash",
      },
    ],
    incomePlan: {
      description:
        "Sample allocation: 25% taxable brokerage, 15% Roth IRA, 15% cash, remainder for living expenses.",
    },
    walletMapNodes: [
      {
        id: "w-btc-cold",
        parentId: null,
        label: "Bitcoin cold wallet",
        order: 0,
        walletType: "bitcoin_cold",
        address: "bc1qdem0sample0000000000000000000000",
        networks: ["bitcoin"],
        links: { assetsSectionId: "sec-btc" },
        status: "active",
      },
    ],
    monthlyIncome: 14200,
    netWorthHistory: [
      { period: "2022-06", netWorth: 485000, totalAssets: 525000, totalLiabilities: 40000, totalCostBasis: 410000 },
      { period: "2022-09", netWorth: 462000, totalAssets: 502000, totalLiabilities: 40000, totalCostBasis: 418000 },
      { period: "2022-12", netWorth: 528000, totalAssets: 568000, totalLiabilities: 40000, totalCostBasis: 435000 },
      { period: "2023-03", netWorth: 598000, totalAssets: 638000, totalLiabilities: 40000, totalCostBasis: 458000 },
      { period: "2023-06", netWorth: 642000, totalAssets: 682000, totalLiabilities: 40000, totalCostBasis: 482000 },
      { period: "2023-09", netWorth: 685000, totalAssets: 725000, totalLiabilities: 40000, totalCostBasis: 512000 },
      { period: "2023-12", netWorth: 752000, totalAssets: 792000, totalLiabilities: 40000, totalCostBasis: 548000 },
      { period: "2024-03", netWorth: 798000, totalAssets: 838000, totalLiabilities: 40000, totalCostBasis: 578000 },
      { period: "2024-06", netWorth: 842000, totalAssets: 877000, totalLiabilities: 35000, totalCostBasis: 612000 },
      { period: "2024-09", netWorth: 918000, totalAssets: 953000, totalLiabilities: 35000, totalCostBasis: 648000 },
      { period: "2024-12", netWorth: 985000, totalAssets: 1020000, totalLiabilities: 35000, totalCostBasis: 692000 },
      { period: "2025-03", netWorth: 1042000, totalAssets: 1077000, totalLiabilities: 35000, totalCostBasis: 728000 },
      { period: "2025-06", netWorth: 1098000, totalAssets: 1133000, totalLiabilities: 35000, totalCostBasis: 768000 },
      { period: "2025-09", netWorth: 1138000, totalAssets: 1173000, totalLiabilities: 35200, totalCostBasis: 812000 },
      { period: "2025-12", netWorth: 1172000, totalAssets: 1207200, totalLiabilities: 35200, totalCostBasis: 856000 },
      { period: "2026-03", netWorth: 1192000, totalAssets: 1227200, totalLiabilities: 35200, totalCostBasis: 912000 },
      { period: "2026-05", netWorth: 1204250, totalAssets: 1239450, totalLiabilities: 35200, totalCostBasis: 996000 },
    ],
    uiPreferences: {
      theme: "system",
      navPages: {
        overview: true,
        assets: true,
        cash: true,
        liabilities: true,
        wallets: true,
        plan: true,
      },
      planTabs: { income: true, wallets: false, budget: true, goals: true },
      overviewChart: DEFAULT_OVERVIEW_CHART,
      overviewWidgets: DEFAULT_OVERVIEW_WIDGETS,
      sidebarCompact: false,
      monthlyAutoSnapshot: false,
      netWorthSnapshotCadence: "month",
    },
  };
}
